### ISSUE TITLE
Unused Flow Resources

### ISSUE THREAD

**Issue by jackvaughanjr** [okta/workflows-templates#117]
In the [Modernize your Access Request Management with Okta and Slack](../tree/master/workflows/access_request_with_slack) template, there are resources that _I believe_ were updated or deprecated but weren't removed from the flow?

In `Request.Apps.02.01. SlackBot.SubmitRequestToManager`, there are references to `Approval URL` and `Deny URL` fields that no longer exist in the `Variables` table.

Additionally, there are subsequent Text-Concatenate cards with `denyUrl` and `approvalUrl` outputs that are not used anywhere else in the flow.

![image](https://user-images.githubusercontent.com/14348267/147002133-bf1339b3-5676-4794-a92a-6e2a1045fb5e.png)
![image](https://user-images.githubusercontent.com/14348267/147002150-e371b16c-a0e5-4d00-a44b-698ba12a4b17.png)

**Comment by maxkatz** [comment]
Hi, 

This template is no longer available.

**Comment by IanHakes-okta** [comment]
Closing issue as template is no longer available.
