### ISSUE TITLE
Incomplete Card Configuration

### ISSUE THREAD

**Issue by jackvaughanjr** [okta/workflows-templates#118]
In the [Modernize your Access Request Management with Okta and Slack](../tree/master/workflows/access_request_with_slack) template > flow `Request.Approval.02. SlackBot.RejectedTrigger`, the first `Tables - Search Rows` card is missing its' Where Expression. It should be `Where ( "Token" = token )`.

![image](https://user-images.githubusercontent.com/14348267/147138205-ed799a0f-998e-4546-84a6-1d6c8ab3d862.png)
![image](https://user-images.githubusercontent.com/14348267/147138461-20a2ff80-06f3-48ab-bf7a-d5eef2e32569.png)

**Comment by maxkatz** [comment]
Hi, 

This template is no longer available.

**Comment by maxkatz** [comment]
Hi @deduced - the template existed to fill a gap until [OIG](https://www.okta.com/products/identity-governance/) was released. The template was complex and challenging to modify.

**Comment by IanHakes-okta** [comment]
Closed as template has been removed.
