### ISSUE TITLE
Accompanying video mentioned on readme

### ISSUE THREAD

**Issue by stormynp** [okta/workflows-templates#150]
"Generate Unique Okta Usernames" template.

Can't find a video to watch.

This link got me here:
https://xxxxxxxx.workflows.oktapreview.com/app/templates/generate_unique_username

But the linked "Video Walk through" is a non-viewable PRIVATE Youtube video. We can't view it.

https://www.youtube.com/watch?v=JEk33EdlV2A

**Comment by maxkatz** [comment]
Hi, 

The template has been updated to this template: https://github.com/okta/workflows-templates/blob/master/workflows/generate_unique_username_with_user_import_inline_h/readme.md. It doesn't have a video today.

**Comment by IanHakes-okta** [comment]
As Max mentioned, the original template with the issue has been changed to one without a video link. Resolving the issue here.
