### ISSUE TITLE
Group Principle 

### ISSUE THREAD

**Issue by SonyDavid** [okta/workflows-templates#163]
If we're using SCIM for Okta, when the group is pushed by Okta, AWS creates the group principle ID. Is there a way to capture that to create a workflow the populates that into a table ?

**Comment by maxkatz** [comment]
Hi, 

There is no exposed API for the push group.  You need a webhook on the AWS side that would trigger a flow based on this activity.

**Comment by IanHakes-okta** [comment]
Closing issue based on Max's response.
