### ISSUE TITLE
Raw HTTP Connector to GSuite Refresh Token

### ISSUE THREAD

**Issue by mjtrain3** [okta/workflows-templates#80]
The Raw HTTP Connector to GSuite workflow does not receive a refresh token and requires re-authentication every hour.

https://github.com/okta/workflows-templates/blob/master/workflows/raw_http_connection_gsuite/readme.md

**Comment by bryanbarrows-okta** [comment]
Thanks for reporting this @mjtrain3 - we added a note to the Known Limitations section. As our Google connectors mature, hopefully this template will become less necessary. Thanks again!
